### ISSUE TITLE
New API - get volunteer list from spark

### ISSUE THREAD

**Issue by guywarburg** [Midburn/volunteers#27]
Create a connection with spark to get data.

(This should complete the first screen that displays the whole volunteer list)

**Comment by eyalliebermann** [comment]
Here's a suggested api based on the one @may-ben-arie @mbenarie has posted [here](https://docs.google.com/document/d/1QquLZZl8kO_-_Wv58OtJjGd0sDbWSUl6z12Mq56vzZI)


GET /volunteers/
returns
[
{
	"departmnet_id" : 7
        "department_name": "Medical",
	"user_id": 17,
	"first_name": "May",
	"last_name": "Ben Arie",
	"email": "may@gmail.com",
	"phone_number": "0541234567",
        "role": "Department Manager",
        "volunteer_type": "Day Manager",
	"got_ticket": true,
       "is_production":false
},
...
...
...
]

Currently all REST routes for a single action are of the form volunteer/department
since we're manipulating the volunteer assignment to the department I think it should be
departments/:department_id/volunteers
This make sense as long as department::volunteer is a one to many relationship. one group has many volunteer but a single volunteer belongs only to one department

Alternatively we could create an assignement_id to describe the a department::volunteer many to many relationship and make all deletion/editing actions on the route /assignments/:assignment_id

where assignment is the term I termporarily use here to describe a volunteer belonging to a certain department.


GET /departments/{department_id}/volunteers (next task)
returns a list of users relevant to the department
[
{
	"departmnet_id" : 7
        "department_name": "Medical",
	"user_id": 17,
	"first_name": "May",
	"last_name": "Ben Arie",
	"email": "may@gmail.com",
	"phone_number": "0541234567",
        "role": "Department Manager",
        "volunteer_type": "Day Manager",
	"got_ticket": true,
       "is_production":false
},
...
...
...
]

GET /volunteers/me   -- (future task)

**Comment by eyalliebermann** [comment]
done
